name: Deploy to AWS EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the code
    - name: Checkout code
      uses: actions/checkout@v3

    # Step 2: Log in to Docker Hub
    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    # Step 3: Build and push the Docker image
    - name: Build and push Docker image
      run: |
        docker build -t coder1971/cicd-express-app:latest .
        docker push coder1971/cicd-express-app:latest
   # Step 4: SSH into EC2 and pull the Docker image
    - name: Deploy to AWS EC2
      uses: appleboy/ssh-action@v0.1.9
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          docker pull coder1971/cicd-express-app:latest
          docker stop app || true
          docker rm app || true
          docker run -d --name app -p 80:3000 coder1971/cicd-express-app:latest

